const SOURCE_TYPES = {
  ALL_SOURCES: 'all',
  GURU_GRANTH_SAHIB: 'G',
  DASAM_GRANTH: 'D',
  GURDAS_VAARAN: 'B',
  NAND_LAL_VAARAN: 'N',
  AMRIT_KEERTAN: 'A',
  GURDAS_JI_VAARAN: 'S',
  REHATNAMAS: 'R',
} as const;

const SOURCE_TEXTS: Record<string, string> = {
  [SOURCE_TYPES.ALL_SOURCES]: 'ALL_SOURCES',
  [SOURCE_TYPES.GURU_GRANTH_SAHIB]: 'GURU_GRANTH_SAHIB',
  [SOURCE_TYPES.DASAM_GRANTH]: 'DASAM_GRANTH',
  [SOURCE_TYPES.GURDAS_VAARAN]: 'GURDAS_VAARAN',
  [SOURCE_TYPES.NAND_LAL_VAARAN]: 'NAND_LAL_VAARAN',
  [SOURCE_TYPES.AMRIT_KEERTAN]: 'AMRIT_KEERTAN',
  [SOURCE_TYPES.GURDAS_JI_VAARAN]: 'GURDAS_JI_VAARAN',
  [SOURCE_TYPES.REHATNAMAS]: 'REHATNAMAS',
};

const WRITER_TYPES = {
  ALL_WRITERS: 'all',
  GURU_NANAK_DEV: 1,
  GURU_ANGAD_DEV: 2,
  GURU_AMAR_DAS: 3,
  GURU_RAM_DAS: 4,
  GURU_ARJAN_DEV: 5,
  GURU_TEGH_BAHADUR: 6,
  OTHERS: 'others',
} as const;

const WRITER_TEXTS: Record<string | number, string> = {
  [WRITER_TYPES.ALL_WRITERS]: 'ALL_WRITERS',
  [WRITER_TYPES.GURU_NANAK_DEV]: 'GURU_NANAK_DEV',
  [WRITER_TYPES.GURU_ANGAD_DEV]: 'GURU_ANGAD_DEV',
  [WRITER_TYPES.GURU_AMAR_DAS]: 'GURU_AMAR_DAS',
  [WRITER_TYPES.GURU_RAM_DAS]: 'GURU_RAM_DAS',
  [WRITER_TYPES.GURU_ARJAN_DEV]: 'GURU_ARJAN_DEV',
  [WRITER_TYPES.GURU_TEGH_BAHADUR]: 'GURU_TEGH_BAHADUR',
  [WRITER_TYPES.OTHERS]: 'OTHERS',
};

const RAAG_TYPES = {
  ALL_RAAGS: 'all',
  ASA: 8,
  GUJARI: 9,
  DHANASARI: 14,
  SRI: 5,
  MAJH: 6,
  GAURI: 7,
  OTHERS: 'others',
} as const;

const RAAG_TEXTS: Record<string | number, string> = {
  [RAAG_TYPES.ALL_RAAGS]: 'ALL_RAAGS',
  [RAAG_TYPES.ASA]: 'ASA',
  [RAAG_TYPES.GUJARI]: 'GUJARI',
  [RAAG_TYPES.DHANASARI]: 'DHANASARI',
  [RAAG_TYPES.SRI]: 'SRI',
  [RAAG_TYPES.MAJH]: 'MAJH',
  [RAAG_TYPES.GAURI]: 'GAURI',
  [RAAG_TYPES.OTHERS]: 'OTHERS',
};

export default {
  SOURCE_TEXTS,
  WRITER_TEXTS,
  RAAG_TEXTS,
};
